{% set name = "git-remote-codecommit" %}
{% set version = "1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8e10cc5c177486022e4e7c2c08e671ed35ad63f3a2da1309a1f8eae7b6e69da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - git-remote-codecommit = git_remote_codecommit:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - botocore >=1.17.0

test:
  imports:
    - git_remote_codecommit
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/aws/git-remote-codecommit
  summary: A Git extension for pushing and pulling from AWS CodeCommit.
  description: |
    This package enables pushing and pulling from repository URLs prefixed with codecommit://
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/aws/git-remote-codecommit
  dev_url: https://github.com/aws/git-remote-codecommit

extra:
  recipe-maintainers:
    - SylvainCorlay
